### ISSUE TITLE
useSelector Hook never sees the initialStore

### ISSUE THREAD

**Issue by xvaldetaro** [thomashoneyman/purescript-halogen-store#18]
When using `useSelector` in my Hook I notice that I get `Nothing` until I call `updateStore` with something. After that I get whatever value was in the initialStore plus my update. Is this intended?

**Comment by thomashoneyman** [comment]
No, that doesn't sound right. It looks like the implementation is a bit off (I haven't yet used `useSelector` myself, so I haven't encountered this issue).

The hook begins by initializing the local state to `Nothing`:
https://github.com/thomashoneyman/purescript-halogen-store/blob/7dbf39dd1c31d083fd3822fb1339b2052b1e8260/src/Halogen/Store/UseSelector.purs#L28

This corresponds with the `connect` higher-order-component, which does the same thing:
https://github.com/thomashoneyman/purescript-halogen-store/blob/7dbf39dd1c31d083fd3822fb1339b2052b1e8260/src/Halogen/Store/Connect.purs#L54-L58

Next, the hook initializes a subscription, indicating that the local state should be updated when the store updates:
https://github.com/thomashoneyman/purescript-halogen-store/blob/7dbf39dd1c31d083fd3822fb1339b2052b1e8260/src/Halogen/Store/UseSelector.purs#L30-L33

This corresponds with the `subscribe` helper function used in the `connect` component:
https://github.com/thomashoneyman/purescript-halogen-store/blob/7dbf39dd1c31d083fd3822fb1339b2052b1e8260/src/Halogen/Store/Connect.purs#L102-L104

Unfortunately, the hook stops there, but there's still one last thing to do: read the current value of the store and set it in state. You can see that is done in the `connect` component during initialization:
https://github.com/thomashoneyman/purescript-halogen-store/blob/7dbf39dd1c31d083fd3822fb1339b2052b1e8260/src/Halogen/Store/Connect.purs#L75-L78

But this never happens in the hook. The hook needs to also select the current value from the store and update the local state.

Would you be interested in contributing a patch that fixes this issue as I've described, @xvaldetaro? If not, I can do so myself in the next day or two.

**Comment by xvaldetaro** [comment]
yea, let me take a crack at it. I'm still very uncomfortable with Purescript so I might need some time to slowly read the code and try to make sense of the monad magic there :)

**Comment by thomashoneyman** [comment]
Great! I would use the implementation in ‘connect’ as your guide.

**Comment by thomashoneyman** [comment]
Closed in #19
